name: K210 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: K210 Toolchain Setup
      run: |
        sudo apt install build-essential cmake
        wget https://s3.cn-north-1.amazonaws.com.cn/dl.kendryte.com/documents/kendryte-toolchain-ubuntu-amd64-8.2.0-20190213.tar.gz
        tar zxvf kendryte-toolchain-ubuntu-amd64-8.2.0-20190213.tar.gz
    - name: Build
      run: |
        export PATH=$(pwd)/kendryte-toolchain/bin:${PATH}
        export K210_TOOLCHAIN=$(pwd)/kendryte-toolchain/bin
        mkdir build && cd build
        cmake .. -DPROJ=genplus -DSDK_ROOT=./kendryte-standalone-sdk -DTOOLCHAIN=${K210_TOOLCHAIN}
        make
